name: 'bitcoin'

on:
  push:
    branches: 
      - master
#   schedule:
#     - cron: '*/10 *  * * *'
jobs:
  GetBtcPrice:
    runs-on: ubuntu-latest
    steps:
    - name: 'Checkout codes'
      uses: actions/checkout@v2
    - name: 'Setup python'
      uses: actions/setup-python@v1
      with:
        python-version: '3.x'
    - name: 'Install dependencies'
      run: python -m pip install --upgrade requests lxml jinja2 
    - name: 'run get price script'
      env:
        MAX: ${{ secrets.MAX }}
        MIN: ${{ secrets.MIN }}
      run: python bitcoin.py
    - name: Send mail
      if: ${{ env.sendemail == 'True' }}
      uses: dawidd6/action-send-mail@v2
      with:
        server_address: smtp.163.com
        server_port: 465
        username: ${{secrets.MAIL_USERNAME}}
        password: ${{secrets.MAIL_PASSWORD}}
        subject: 比特币价格监控
        # Literal body:
        body: file://email.html
        to: ${{ secrets.TO }}
        from: ${{secrets.MAIL_USERNAME}} # <user@example.com>
        # Optional content type (defaults to text/plain):
        content_type: text/html
